"""Select ~500 geo-balanced METAR stations for the v2 corpus (Session 19).

The v1 corpus (51 stations) was 74% US *by observation volume* — US ASOS reports
sub-hourly (~5 min) vs half-hourly elsewhere, a 6:1 gap that swamps the regional
messy tail the finetune actually targets. v2 fixes that at the source: pull a station
budget spread across regions with the US deliberately capped, so no single geography
dominates by station count — and later cadence-downsample the remaining US high-freq
sites so it can't dominate by volume either.

Source: IEM's per-country ASOS network geojson (`geojson/network/<ISO2>__ASOS.geojson`),
which lists every station with its id (ICAO), name, and archive span. We keep only
currently-online stations with pre-2024 history (so they have data across both the
train and post-cutoff eval windows), cap per country, dedupe against the existing v1
set, and write the union to configs/stations_v2.yaml.
"""

from __future__ import annotations

import time
from pathlib import Path

import httpx
import yaml

NET_URL = "https://mesonet.agron.iastate.edu/geojson/network/{net}__ASOS.geojson"
CONFIG_DIR = Path(__file__).resolve().parents[3] / "configs"
V1 = CONFIG_DIR / "stations.yaml"
OUT = CONFIG_DIR / "stations_v2.yaml"

# Region -> ISO2 country codes whose ASOS networks IEM carries. Chosen for geographic
# spread and for formats that stress the decoder (CIS/China MPS winds, Nordic regional
# extensions, fractional-SM US-adjacent). US is handled separately (reuse v1's, capped).
REGIONS: dict[str, list[str]] = {
    "eu": ["FR", "DE", "GB", "ES", "IT", "NO", "SE", "FI", "DK", "NL", "BE", "CH",
           "AT", "CZ", "PT", "IE", "GR", "RO", "HU", "HR", "RS", "BG", "SK", "IS"],
    "asia": ["JP", "CN", "KR", "IN", "TH", "VN", "MY", "ID", "PH", "TW", "LK", "PK", "KH", "MM"],
    "cis": ["RU", "UA", "KZ", "BY", "UZ", "GE", "AM", "AZ"],
    "mideast": ["SA", "AE", "IR", "IQ", "TR", "IL", "JO", "KW", "QA", "OM", "LB", "BH"],
    "africa": ["ZA", "EG", "MA", "KE", "NG", "DZ", "TN", "ET", "GH", "SN", "TZ"],
    "samerica": ["BR", "AR", "CL", "CO", "PE", "VE", "EC", "BO", "PY", "UY"],
    "oceania": ["AU", "NZ", "FJ", "PG"],
    "namerica": ["CA", "MX", "GT", "CU", "PA", "CR", "DO"],  # non-US N.America
}
CAP_PER_COUNTRY = 6          # major-airport-ish sample; keeps any one country from dominating
HISTORY_BEFORE = "2024-01-01"  # archive_begin must precede this -> data across both splits


def _fetch(net: str) -> list[dict]:
    try:
        r = httpx.get(NET_URL.format(net=net), timeout=40)
        r.raise_for_status()
        return r.json().get("features", [])
    except Exception as e:  # noqa: BLE001 — a missing/again network must not abort the sweep
        print(f"  {net}__ASOS: skip ({type(e).__name__})")
        return []


def _pick(features: list[dict], cap: int, exclude: set[str]) -> list[dict]:
    """Online stations with pre-2024 history, id not already taken, up to `cap`."""
    out = []
    for f in features:
        p = f.get("properties", {})
        sid = f.get("id", "")
        if sid in exclude or len(sid) != 4:
            continue
        if not p.get("online"):
            continue
        ab = p.get("archive_begin")
        if not ab or ab >= HISTORY_BEFORE:
            continue
        out.append({"icao": sid, "name": (p.get("sname") or "").strip()})
        if len(out) >= cap:
            break
    return out


def main() -> None:
    existing = {s["icao"] for s in yaml.safe_load(V1.read_text())["stations"]}
    taken = set(existing)
    selected: list[dict] = []
    by_region: dict[str, int] = {}
    for region, countries in REGIONS.items():
        for cc in countries:
            picks = _pick(_fetch(cc), CAP_PER_COUNTRY, taken)
            for pk in picks:
                pk["region"] = region
                pk["country"] = cc
                taken.add(pk["icao"])
            selected.extend(picks)
            by_region[region] = by_region.get(region, 0) + len(picks)
            time.sleep(0.3)  # polite between network calls
        print(f"{region:9} +{by_region.get(region,0)} stations")

    print(f"\nNEW stations: {len(selected)}  |  + v1 existing: {len(existing)}  "
          f"=  {len(selected)+len(existing)} total")
    OUT.write_text(
        "# v2 station set — geo-balanced, US-capped (Session 19). Generated by\n"
        "# `python -m avtext.ingest.select_stations`; union of v1 + new non-US picks.\n"
        f"# new={len(selected)} + v1={len(existing)} = {len(selected)+len(existing)}\n\n"
        + yaml.safe_dump(
            {"stations": [{"icao": s["icao"], "name": s["name"], "region": s["region"],
                           "country": s["country"]} for s in selected]},
            sort_keys=False, allow_unicode=True,
        )
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
